#pragma once

#include <stdbool.h>

#include <SDL3/SDL.h>

#include "utils/base-types.h"

typedef enum AquaEventType {
	AQUA_EVENT_TYPE_NONE,
	AQUA_EVENT_TYPE_EXIT,
	AQUA_EVENT_TYPE_WINDOW_RESIZED,
	AQUA_EVENT_TYPE_WINDOW_PIXEL_SIZE_CHANGED,
	AQUA_EVENT_TYPE_WINDOW_LEAVE_FULLSCREEN,
	AQUA_EVENT_TYPE_KEY_UP,
	AQUA_EVENT_TYPE_KEY_DOWN,
	AQUA_EVENT_TYPE_MOUSE_MOTION
} AquaEventType;

typedef struct AquaEventWindow {
	u32 new_width;
	u32 new_height;
} AquaEventWindow;

typedef enum AquaEventKeyScancode {
	AQUA_SCANCODE_A = 4,
    AQUA_SCANCODE_B = 5,
    AQUA_SCANCODE_C = 6,
    AQUA_SCANCODE_D = 7,
    AQUA_SCANCODE_E = 8,
    AQUA_SCANCODE_F = 9,
    AQUA_SCANCODE_G = 10,
    AQUA_SCANCODE_H = 11,
    AQUA_SCANCODE_I = 12,
    AQUA_SCANCODE_J = 13,
    AQUA_SCANCODE_K = 14,
    AQUA_SCANCODE_L = 15,
    AQUA_SCANCODE_M = 16,
    AQUA_SCANCODE_N = 17,
    AQUA_SCANCODE_O = 18,
    AQUA_SCANCODE_P = 19,
    AQUA_SCANCODE_Q = 20,
    AQUA_SCANCODE_R = 21,
    AQUA_SCANCODE_S = 22,
    AQUA_SCANCODE_T = 23,
    AQUA_SCANCODE_U = 24,
    AQUA_SCANCODE_V = 25,
    AQUA_SCANCODE_W = 26,
    AQUA_SCANCODE_X = 27,
    AQUA_SCANCODE_Y = 28,
    AQUA_SCANCODE_Z = 29,

    AQUA_SCANCODE_1 = 30,
    AQUA_SCANCODE_2 = 31,
    AQUA_SCANCODE_3 = 32,
    AQUA_SCANCODE_4 = 33,
    AQUA_SCANCODE_5 = 34,
    AQUA_SCANCODE_6 = 35,
    AQUA_SCANCODE_7 = 36,
    AQUA_SCANCODE_8 = 37,
    AQUA_SCANCODE_9 = 38,
    AQUA_SCANCODE_0 = 39,

    AQUA_SCANCODE_RETURN = 40,
    AQUA_SCANCODE_ESCAPE = 41,
    AQUA_SCANCODE_BACKSPACE = 42,
    AQUA_SCANCODE_TAB = 43,
    AQUA_SCANCODE_SPACE = 44,

    AQUA_SCANCODE_MINUS = 45,
    AQUA_SCANCODE_EQUALS = 46,
    AQUA_SCANCODE_LEFTBRACKET = 47,
    AQUA_SCANCODE_RIGHTBRACKET = 48,
    AQUA_SCANCODE_BACKSLASH = 49,
    AQUA_SCANCODE_NONUSHASH = 50,
    AQUA_SCANCODE_SEMICOLON = 51,
    AQUA_SCANCODE_APOSTROPHE = 52,
    AQUA_SCANCODE_GRAVE = 53,
    AQUA_SCANCODE_COMMA = 54,
    AQUA_SCANCODE_PERIOD = 55,
    AQUA_SCANCODE_SLASH = 56,

    AQUA_SCANCODE_CAPSLOCK = 57,

    AQUA_SCANCODE_F1 = 58,
    AQUA_SCANCODE_F2 = 59,
    AQUA_SCANCODE_F3 = 60,
    AQUA_SCANCODE_F4 = 61,
    AQUA_SCANCODE_F5 = 62,
    AQUA_SCANCODE_F6 = 63,
    AQUA_SCANCODE_F7 = 64,
    AQUA_SCANCODE_F8 = 65,
    AQUA_SCANCODE_F9 = 66,
    AQUA_SCANCODE_F10 = 67,
    AQUA_SCANCODE_F11 = 68,
    AQUA_SCANCODE_F12 = 69,

    AQUA_SCANCODE_PRINTSCREEN = 70,
    AQUA_SCANCODE_SCROLLLOCK = 71,
    AQUA_SCANCODE_PAUSE = 72,
    AQUA_SCANCODE_INSERT = 73,
    AQUA_SCANCODE_HOME = 74,
    AQUA_SCANCODE_PAGEUP = 75,
    AQUA_SCANCODE_DELETE = 76,
    AQUA_SCANCODE_END = 77,
    AQUA_SCANCODE_PAGEDOWN = 78,
    AQUA_SCANCODE_RIGHT = 79,
    AQUA_SCANCODE_LEFT = 80,
    AQUA_SCANCODE_DOWN = 81,
    AQUA_SCANCODE_UP = 82,
} AquaEventKeyScancode;

typedef struct AquaEventKey {
	AquaEventKeyScancode scancode;
} AquaEventKey;

typedef struct AquaEventMouseMotion {
    f32 x, y;
    f32 x_relative, y_relative;
} AquaEventMouseMotion;

typedef struct AquaEvent {
	SDL_Event sdl_event;

	AquaEventType type;

	AquaEventWindow window;
	AquaEventKey key;
	AquaEventMouseMotion mouse_motion;
} AquaEvent;

bool aqua_event_poll(AquaEvent* event);
